--- #YAML:1.0
name:               Imager-Font-FT2
version:            0.88
abstract:           FreeType 2 font driver for Imager
author:
    - Tony Cook <tonyc@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
    Imager:               0.94
build_requires:
    ExtUtils::MakeMaker:  0
    Imager:               0.94
    Test::More:           0.47
requires:
    Imager:        0.94
    Scalar::Util:  1
    XSLoader:      0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Imager
    homepage:    http://imager.perl.org/
    repository:  git://git.imager.perl.org/imager.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
